user_management/urls.py
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView
from users import views

from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

    path('show',views.show, name='show'),  
    path('adminlogin/', views.login, name='admin_login'),

    path('addnew',views.addnew, name='addnew'),  
    path('edit/<int:id>', views.edit, name='edit'),  
    path('update/<int:id>', views.update, name='update'),  
    path('delete/<int:id>', views.destroy, name='destroy'),  

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import home,RegisterView

urlpatterns = [
    path('', home, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
]

users/models.py
from django.db import models

 
# Create your models here.
class Employee(models.Model):


    trade = models.CharField(max_length=100) 
    date = models.CharField(max_length=100)
    shares = models.CharField(max_length=100)
    symbols = models.CharField(max_length=100)
    buysell = models.CharField(max_length=100)
    payment = models.CharField(max_length=100)
    userid = models.CharField(max_length=100)
    age = models.CharField(max_length=100)


    username = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

   
    class Meta:  
        db_table = "tblemployee"


        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'User ID',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Age',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']



from django import forms  
from users.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = ['trade', 'date', 'shares', 'symbols', 'buysell', 'payment', 'userid', 'age', 'username', 'email'] 
        widgets = { 'trade': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'date': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'shares': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'symbols': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'buysell': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'payment': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'userid': forms.TextInput(attrs={ 'class': 'form-control' }), 
                                      'age': forms.TextInput(attrs={ 'class': 'form-control' }), 

                   'username': forms.TextInput(attrs={ 'class': 'form-control' }), 
                   'email': forms.TextInput(attrs={ 'class': 'form-control' }), 

            
      }
        

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, LoginForm

def home(request):
    
    return render(request, 'users/home.html')


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


# Class based view that extends from the built in login view to add a remember me functionality
class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)
    


from users.forms import EmployeeForm  
from users.models import Employee  


 
# Create your views here.  
def addnew(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass
    else:  
        form = EmployeeForm()  
    return render(request,'users/addnew.html',{'form':form})  

 


def home(request):  
    employees = Employee.objects.all()   
    return render(request,"users/home.html",{'employees':employees})  
 
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'users/edit.html', {'employee':employee})  
 
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("show")  
    return render(request, 'users/edit.html', {'employee': employee})  
     
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("show")  

from django.contrib import messages

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        age = request.POST.get('age')

        password = request.POST.get('password')

        if username == 'admin123' and password == 'admin123' and age == 'admin123' :
            # Authentication successful
            request.session['is_authenticated'] = True  # Set a session variable
            return redirect('show')
        else:
            messages.error(request, 'Invalid credentials. Please try again.')
    return render(request, 'users/adminlogin.html')

def show(request):
    if not request.session.get('is_authenticated'):
        return redirect('adminlogin')  # Redirect to login page if not authenticated

    # Assuming you have some logic to retrieve employee data
    employees = Employee.objects.all()
    return render(request, 'users/show.html', {'employees': employees})

users/templates/users/addnew.html
{% extends "users/base.html" %}
  
  
{% block content %}
<h1 class="display-4">Welcome, {{user.username.title|default:'Guest'}}</h1>
        <p class="lead">
        </p>
        <hr class="my-4">

        <a href="/" class="button">Back to Dashboard</a>

            <h1>NEW TRADE</h1>
            <form method="POST" class="post-form" action="/addnew">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="userid"><b>USER ID:</b></label>
                    <input type="text" class="form-control grayed-out" id="userid" name="userid" value="{{ user.first_name|default:'' }}" readonly>
                </div>
                <div class="mb-3">
                    <label for="username"><b>USERNAME:</b></label>
                    <input type="text" class="form-control grayed-out" id="username" name="username" value="{{ user.username|default:'' }}" readonly>
                </div>

                <div class="mb-3">
                    <label for="age"><b>AGE:</b></label>
                    <input type="text" class="form-control grayed-out" id="age" name="age" value="{{ user.last_name|default:'' }}" readonly>
                </div>


                <div class="mb-3">
                    <label for="email"><b>EMAIL:</b></label>
                    <input type="text" class="form-control grayed-out" id="email" name="email" value="{{ user.email|default:'' }}" readonly>
                </div>
                <label for="a">-------------------------------------------------------------------------------------</label>


                <div class="mb-3">
                    <label for="trade"><b>TRADE ID:</b></label>
                    <input type="text"  id="tradeId" name="trade" readonly>
                </div>
                
                <script>
                    // Function to generate a unique trade ID
                    function generateTradeId() {
                        // You can implement your own logic to generate a unique ID here.
                        // For simplicity, let's use a timestamp-based ID here.
                        const timestamp = Date.now();
                        return `${timestamp}`;
                    }
                
                    // Automatically generate the trade ID when the page loads
                    const tradeIdField = document.getElementById('tradeId');
                    if (tradeIdField) {
                        // Generate a unique trade ID
                        const uniqueTradeId = generateTradeId();
                        // Set the generated ID in the input field
                        tradeIdField.value = uniqueTradeId;
                    }
                </script>
                
                <div class="mb-3">
                    <label for="date"><b>DATE OF EXECUTION:</b></label>
                    {{ form.date }}
                </div>
                
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
                
                <style>

.grayed-out {
            background-color: #f0f0f0; /* Set the background color to a light gray */
            color: #888; /* Set the text color to a darker gray */
            
        }
                    /* Style the date picker calendar */
                    .ui-datepicker {
                        background-color: white; /* Set the background color to white */
                    }
                </style>
                
                <script>
                    $(function() {
                        $("#id_date").datepicker();
                    });
                </script>
                <div class="mb-3">
                    <label for="shares"><b>AMOUNT OF SHARES BOUGHT:</b></label>
                    {{ form.shares }}
                </div>
                <div class="mb-3">
                    <label for="symbols"><b>SYMBOL OF SHARE:</b></label>
                    {{ form.symbols }}
                </div>
                <div class="mb-3">
                    <label for="buysell"><b>BUY/SELL:</b></label>
                    <select name="buysell" id="buysell">
                        <option value="BOUGHT">BOUGHT</option>
                        <option value="SOLD">SOLD</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="payment"><b>TOTAL PAYMENT:</b></label>
                    {{ form.payment }}
                </div>
                <div class="mb-3">
                    <button type="submit" class="button">Submit</button>

                </div>
            </form>


{% endblock content %} 

users/templates/users/adminlogin.html
{% extends "users/base.html" %}
{% block title %} Login Page {% endblock title%}
{% block content %}

                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h1 class="font-weight-light my-1 text-left">Admin Safe</h1>
                          <label for=""><b>" admin123 "</b> is the Keypass for username, age, password </label>
                          <hr class="my-4">


                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" id="id" name="id" class="form-control" placeholder="1923849142" readonly>
                                </div>
                                <div class="form-group">
                                    <input type="text" id="username" name="username" class="form-control" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <input type="text" id="age" name="age" class="form-control" placeholder="Age">
                                </div>
                                <div class="form-group">
                                    <input type="password" id="password" name="password" class="form-control" placeholder="Password">
                                </div>


                                    <button type="submit" class="button">Access Admin</button>
                                    <div class="card-footer text-left">
                                        <div class="small">
                                            <a href="{% url 'users-register' %}">Don't have an account yet? Go to signup</a><br>
                                        </div>
                                    </div>

                                   
                            </form>
                        </div>

                    </div>

{% endblock content %}

users/templates/users/edit.html
{% extends "users/base.html" %}
  
{% block title %}Employee Records{% endblock title %}
  

{% block content %}
{% load static %}  
<link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css"/>
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
<h1 class="font-weight-light my-1 text-left">Admin Dashboard</h1>
<hr class="my-4">

<h1>EDIT TRADE</h1>
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
    {% csrf_token %}
    <style>
        .grayed-out {
            background-color: #f0f0f0; /* Set the background color to a light gray */
            color: #888; /* Set the text color to a darker gray */
            
        }

        
    </style>

    <div class="mb-3">
        <label><b>USER ID:</b></label>  
        <input type="text" class="form-control grayed-out" name="userid" id="id_userid" required maxlength="50" value="{{ employee.userid }}" readonly  />
    </div>
    
    <div class="mb-3">
        <label><b>USERNAME:</b></label>  
        <input type="text" class="form-control grayed-out" name="username" id="id_username" required maxlength="50" value="{{ employee.username }}" readonly />
    </div>

    <div class="mb-3">
        <label><b>AGE:</b></label>  
        <input type="text" class="form-control grayed-out" name="age" id="id_age" required maxlength="50" value="{{ employee.age }}"readonly />
    </div>


    <div class="mb-3">
        <label><b>EMAIL:</b></label>  
        <input type="text" class="form-control grayed-out" name="email" id="id_email" required maxlength="50" value="{{ employee.email }}" readonly/>
    </div>


    <div class="mb-3">
        <label><b>TRADE ID:</b></label>  
        <input type="text" class="form-control grayed-out" name="trade" id="id_trade" required maxlength="50" value="{{ employee.trade }}" readonly/>
    </div>

    <div class="mb-3">
        <label><b>DATE OF EXECUTION:</b></label>  
        <input type="text" class="form-control grayed-out" name="date" id="id_date" required maxlength="50" value="{{ employee.date }}" readonly/>
    </div>
    <div class="mb-3">
        <label><b>SYMBOL OF SHARE:</b></label>  
        <input type="text" class="form-control grayed-out" name="symbols" id="id_symbols" required maxlength="50" value="{{ employee.symbols }}" readonly />
    </div>
    <div class="mb-3">
        <label><b>BUY/SELL:</b></label>  
        <input type="text" class="form-control grayed-out" name="buysell" id="id_buysell" required maxlength="50" value="{{ employee.buysell }}" readonly />
    </div>
    <label>-------------------------------------------------------------------------------------</label>  
    <div class="mb-3">
        <label><b>AMOUNT OF SHARES BOUGHT:</b></label>  
        <input type="text" class="form-control " name="shares" id="id_shares" required maxlength="50" value="{{ employee.shares }}" />
    </div>
    <div class="mb-3">
        <label><b>TOTAL PAYMENT:</b></label>  
        <input type="text" class="form-control" name="payment" id="id_payment" required maxlength="50" value="{{ employee.payment }}" />
    </div>
    <div class="mb-3">
        <button type="submit" class="button">Submit</button>

    </div>
</form>




<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src = "https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
      "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        "iDisplayLength": 5
       } 
    );
} );
</script>




{% endblock content %}

users/templates/users/home.html
{% extends "users/base.html" %}
{% block title %} Home Page {% endblock title%}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome, {{user.username.title|default:'Guest'}}</h1>
         <p class="lead">
            <b>Cross Options Order Management System</b> <br>
            simplifies trade administration by centralizing trade data, ensuring easy access and scalability for future expansion, all with an eye towards production readiness post-testing.
        </p>
        <hr class="my-4">
        <p class="lead">
            {% if user.is_authenticated %}

            
            <a href="{% url 'addnew' %}" class="button">Create New Trade</a>



            {% load static %}  
<link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css"/>
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
<h1 style="color: black;">HISTORY </h1> 

<form id="dateFilterForm">
    <label for="timeframe">Select Timeframe:</label>
    <select id="timeframe" name="timeframe">
        <option value="all">All Time</option>
        <option value="7">Last 7 Days</option>
        <option value="30">Last 30 Days</option>
        <option value="365">Last 365 Days</option>
    </select>
</form>

<div class="col-md-12">
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-bordered table-hover" style="width: 100%;">
            <thead>
                <tr>
                    <th style="width: 10%;">TRADE ID</th>
                    <th style="width: 20%;">DATE OF EXECUTION</th>
                    <th style="width: 20%;">SHARES BOUGHT</th>
                    <th style="width: 20%;">SYMBOL</th>
                    <th style="width: 15%;">BUY/SELL</th>
                    <th style="border-right: 1px solid #000;">TOTAL PAYMENT</th>

                    <th style="width: 15%;">USER ID</th>
                    <th style="width: 15%;">USERNAME</th>
                    <th style="width: 15%;">AGE</th>
                    <th style="width: 15%;">EMAIL</th>

                </tr>   
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td class="bold-column">{{ employee.trade }}</td>
                    <td>{{ employee.date }}</td>
                    <td>$ {{ employee.shares }}</td>
                    <td>{{ employee.symbols }}</td>
                    <td>{{ employee.buysell }}</td>
                    <td style="border-right: 1px solid #000; color: red;">$ {{ employee.payment }}</td> <!-- Line Column with Red Font Color -->

                    <td class="bold-column">{{ employee.userid }}</td>
                    <td>{{ employee.username }}</td>
                    <td>{{ employee.age }}</td>
                    <td>{{ employee.email }}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<input type="text" id="filterFirstName" placeholder="Filter by username" value="{{user.username.title|default:'Guest'}}" readonly style="display: none;">




<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src = "https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>

<style>

.bold-column {
        font-weight: bold;
    }
    /* Hide the DataTables search bar */
    .dataTables_filter {
        display: none;
    }
</style>
<script>
    $(document).ready(function() {
        // Initialize the DataTable
        var dataTable = $('#bootstrapdatatable').DataTable({     
            "aLengthMenu": [[ 10, 25, -1], [10, 25, "All"]],
            "iDisplayLength": 10
        });
    
        // Add an event listener to the input field for the "input" event
        $('#filterFirstName').on('input', function() {
            var filterValue = $(this).val().toLowerCase(); // Get the entered value and convert to lowercase
            dataTable.search(filterValue).draw(); // Apply the filter and redraw the table
        });
    
        // Trigger the input event to start filtering based on the initial value
        $('#filterFirstName').trigger('input');
    });

    
    </script>





            {% else %}
            <a href="{% url 'login' %}" class="button">Access your account</a>
                
            {% endif %}
        </p>
    </div>

{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}
{% block title %} Login Page {% endblock title%}
{% block content %}

                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h1 class="font-weight-light my-1 text-left">Sign In</h1>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" id="username" name="username" class="form-control" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <input type="password" id="password" name="password" class="form-control" placeholder="Password">
                                </div>


                                    <button type="submit" class="button">Access you account</button>
                                    <div class="card-footer text-left">
                                        <div class="small">
                                            <a href="{% url 'users-register' %}">Don't have an account yet? Go to signup</a><br>
                                        </div>
                                    </div>

                                   
                            </form>
                        </div>

                    </div>

{% endblock content %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h2 class="card-title"><b>Thank you for using Cross Options Order Management System</b></h2>

        <br><hr><a href="{% url 'login' %}" class="button">Sign In Again</a>
        
        </div>
    </div>


{% endblock content %}